### ISSUE TITLE
add vmware provider 

### ISSUE THREAD

**Issue by tfhartmann** [boston-pug/lab-in-a-box#1]
It would be awesome to have the box support additional providers 

``` Vagrant
The box you're attempting to add doesn't support the provider
you requested. Please find an alternate box or use an alternate
provider. Double-check your requested provider to verify you didn't
simply misspell it.

Name: pug/centos-puppetmaster
Address: https://vagrantcloud.com/pug/centos-puppetmaster
Requested provider: ["vmware_desktop", "vmware_fusion", "vmware_workstation"]
```

**Comment by cammoraton** [comment]
I agree - I just ran out of time.  Adding --provider=virtualbox to your vagrant up command will bring it up in the meantime if you're a cool kid that gave Hashicorp money.

**Comment by tfhartmann** [comment]
:laughing:  No worries, I just figured I'd pop the fusion provider on the "todo" list  - I'm totally spoiled with my fusion plugin.

**Comment by cammoraton** [comment]
I've added vmware_desktop boxes for Centos 6.5 / 7.0 / puppetmaster and updated the packer images.  They at least work on VMware Workstation under linux and the packer templates are updated.

E: And just fixed up trusty / scientific / precise.  Couple weird things under workstation - the private net adapter can't give out dhcp or it will fail on vmnet validation - will have to open an issue with Hashicorp about it.

Can you let me know if everything's good in fusion?
